# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf false

install:
  - git submodule init
  - git submodule update
  - (cd .. && git clone https://github.com/pine613/FelicaCashingSystemV2_Settings.git)
  - choco install adobereader

build_script:
  - powershell -NoProfile -ExecutionPolicy Unrestricted -File Build.ps1

deploy: off
